// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1GEcE4nG9VB_XlCgYdgpRX0tmUIPOYo',
    appId: '1:1010638062648:web:45927487137d08358752cd',
    messagingSenderId: '1010638062648',
    projectId: 'assignment-3f0a6',
    authDomain: 'assignment-3f0a6.firebaseapp.com',
    storageBucket: 'assignment-3f0a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFp-JKL4a84kYYXWFvrV6eww6g8jVH6zM',
    appId: '1:1010638062648:android:aa0873e34ca89d178752cd',
    messagingSenderId: '1010638062648',
    projectId: 'assignment-3f0a6',
    storageBucket: 'assignment-3f0a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_P9G3QWdQSFG25XNa66B-cwTAcai-xs',
    appId: '1:1010638062648:ios:62248b91592449448752cd',
    messagingSenderId: '1010638062648',
    projectId: 'assignment-3f0a6',
    storageBucket: 'assignment-3f0a6.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_P9G3QWdQSFG25XNa66B-cwTAcai-xs',
    appId: '1:1010638062648:ios:77fe5aba4b051fe68752cd',
    messagingSenderId: '1010638062648',
    projectId: 'assignment-3f0a6',
    storageBucket: 'assignment-3f0a6.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
